lista = ['BONILLA ORTIZ DANIEL',
         'CABALLERO LUCIA KARLA GABRIELA',
         'AVALOS LOPEZ DAVID',
         'GOMEZ ESPARZA DIANA',
         'BAUTISTA REYES KELLY',
         'VILLA RODRIGUEZ AGUSTIN',
         'PACHECO SANCHEZ SAN GERMAN MARIA FERNANDA',
         'SALAZA TREJO JORGE FRANCISCO',
         'USUARIO DE ZOOM',
         'REYES SANCHEZ GENESIS FRIDA',
         'SUSAN ZURIZADAY GUZMAN GARCIA',-
         'ALISON CAMARGO',-
         'ROJAS PEREZ OSCAR ALEJANDRO',
         'SANCHEZ ESPINOSA VICTORIA LIZBETH',
         'ALEJANDRO ANTONIO LOPEZ DELGADO',-
         'MARIANA SANCHEZ MENDEZ',-
         'CHAIDEZ VANESSA',-
         'MARCO MENDIZABAL ARELLANO',-
         'MARIANO JAIMES ALEJANDRO',-
         'LESLI GARFIAS ROSAS',-
         'INDIRA SANCHEZ PRADO',-
         'DE LAS CASAS MORAN ROSS JESSYE',
         'MARIA FERNANDA ROMERO',-
         'AOKI CRUZ WENDY',
         'MAYRA GARCIA POMPOSO',-
         'AMELLALLI CRUZ',-
         'AKETZALI HERNANDEZ FLORES',-
         'LUCERO MONTOYA PACHECO',-
         'MIRANDA GALICIA KEVIN MAURICIO',
         'ALEJANDRA RAMOS PARRA',-
         'YOSELIN TAPIA',-
         'OMAR MEZA ROSETE',-
         'SAMPERIO CORREA LUIS ANGEL JAIR',
         'JOSELIN VERA ARMENDARIZ',-
         'ABIGAIL CASTAÑEDA S',-
         'LAGUNA VAZQUEZ BRENDA ITZEL',
         'MORENO HERNANDEZ RAUL PABLO',
         'GARCIA HUERTA FRIDA ZYANYA',
         'MARIUS GABRIEL GORI',-
         'RODOLFO GARCIA HERNANDEZ',-
         'LOPEZ ROSALES JENNIFER',
         'EMILIA RENATA PINEDA LOZOYA',-
         'JIMENEZ PEREZ ITZEL',
         'EDGAR ALEJANDRO RIVERA MACHUCA',-
         'RANGEL CORREA ALEJANDRO MANUEL',
         'XIMENA CHAVEZ',-
         'MARIA FERNANDA FLORES RIVERO',-
         'RAMIREZ MARTINEZ ALAN JOEL',
         'PESCINA MEZA EMMANUEL ALEJANDRO',
         'CAYETANO MARTINEZ LIZBETH',
         'TANIA CAMILO',-
         'MEZA GUZMAN MARIANA',
         'CHRISTIAN IRVIN MEJIA ALCANTARA',-
         'HERRERA CRUZ JOHAN OMAR',
         'MACEDO CHAVEZ RAFAEL']
