# Generated by Django 4.1.3 on 2022-11-07 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo_Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='csv')),
            ],
        ),
        migrations.CreateModel(
            name='Ponderacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('exposicion', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('participacion', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('noticia', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fk_alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='listaDeAsistenciaApp.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='fk_ponderacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ponderacion', to='listaDeAsistenciaApp.ponderacion'),
        ),
    ]
