# Generated by Django 4.1.3 on 2022-11-07 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listaDeAsistenciaApp', '0002_alter_alumno_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fk_ponderacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ponderacion', to='listaDeAsistenciaApp.ponderacion'),
        ),
    ]
