# Generated by Django 4.1.3 on 2022-11-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaDeAsistenciaApp', '0003_alter_alumno_fk_ponderacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
