# Generated by Django 5.0 on 2023-12-06 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaDeAsistenciaApp', '0007_alter_ponderacion_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fk_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='listaDeAsistenciaApp.alumno'),
        ),
        migrations.AlterField(
            model_name='ponderacion',
            name='asistencia',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponderacion',
            name='exposicion',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponderacion',
            name='fk_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderaciones', to='listaDeAsistenciaApp.alumno'),
        ),
        migrations.AlterField(
            model_name='ponderacion',
            name='noticia',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponderacion',
            name='participacion',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], default=0, null=True),
        ),
    ]
