# Generated by Django 5.0 on 2023-12-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaDeAsistenciaApp', '0008_alter_asistencia_fk_alumno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponderacion',
            name='asistencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponderacion',
            name='exposicion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponderacion',
            name='noticia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponderacion',
            name='participacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
